apiVersion: v1
kind: Namespace
metadata:
  name: kafka-zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.4
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-postech
  namespace: kafka-zookeeper
spec:
  selector:
    app: kafka-postech
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-postech
  namespace: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-postech
  template:
    metadata:
      labels:
        app: kafka-postech
    spec:
      containers:
        - name: kafka-postech
          image: confluentinc/cp-kafka:7.4.4
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-postech.kafka-zookeeper.svc.cluster.local:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.kafka-zookeeper.svc.cluster.local:2181
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
